-- Ejecutar esto en Supabase → SQL Editor → New Query
-- Crea la tabla de presupuestos para la app de relevamiento eléctrico

create table if not exists presupuestos (
  id                  bigint generated by default as identity primary key,
  nombre              text not null,
  telefono            text,
  direccion           text,
  fecha_relevamiento  date,
  tipo_obra           text default 'nueva',
  notas               text,
  total_materiales    integer default 0,
  total_mano_obra     integer default 0,
  total_general       integer default 0,
  ambientes           integer default 0,
  datos_json          text,
  created_at          timestamptz default now()
);

-- Habilitar acceso público de lectura/escritura (para la app sin login)
alter table presupuestos enable row level security;

create policy "Acceso publico" on presupuestos
  for all using (true) with check (true);

-- Índice para búsquedas por nombre
create index if not exists idx_presupuestos_nombre on presupuestos(nombre);
create index if not exists idx_presupuestos_fecha  on presupuestos(created_at desc);
